#nullable enable

namespace StudentMvcCrud.Views;

partial class StudentView
{
    private System.ComponentModel.IContainer? components = null;
    private TableLayoutPanel layout = null!;
    private FlowLayoutPanel searchPanel = null!;
    private FlowLayoutPanel fieldsPanel = null!;
    private FlowLayoutPanel actionsPanel = null!;
    private FlowLayoutPanel bulkPanel = null!;
    private Label lblSearch = null!;
    private TextBox txtSearch = null!;
    private Button btnFind = null!;
    private Label lblRollNo = null!;
    private TextBox txtRollNo = null!;
    private Label lblName = null!;
    private TextBox txtName = null!;
    private Label lblAssignment = null!;
    private TextBox txtAssignment = null!;
    private Label lblExam = null!;
    private TextBox txtExam = null!;
    private Button btnAdd = null!;
    private Button btnUpdate = null!;
    private Button btnDelete = null!;
    private Button btnClear = null!;
    private Label lblBulk = null!;
    private CheckBox chkName = null!;
    private CheckBox chkAssignment = null!;
    private CheckBox chkExam = null!;
    private Button btnBulkUpdate = null!;
    private Label lblStatus = null!;
    private DataGridView studentsGrid = null!;

    protected override void Dispose(bool disposing)
    {
        if (disposing && components != null) components.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        layout = new TableLayoutPanel();
        searchPanel = new FlowLayoutPanel();
        fieldsPanel = new FlowLayoutPanel();
        actionsPanel = new FlowLayoutPanel();
        bulkPanel = new FlowLayoutPanel();
        lblSearch = new Label();
        txtSearch = new TextBox();
        btnFind = new Button();
        lblRollNo = new Label();
        txtRollNo = new TextBox();
        lblName = new Label();
        txtName = new TextBox();
        lblAssignment = new Label();
        txtAssignment = new TextBox();
        lblExam = new Label();
        txtExam = new TextBox();
        btnAdd = new Button();
        btnUpdate = new Button();
        btnDelete = new Button();
        btnClear = new Button();
        lblBulk = new Label();
        chkName = new CheckBox();
        chkAssignment = new CheckBox();
        chkExam = new CheckBox();
        btnBulkUpdate = new Button();
        lblStatus = new Label();
        studentsGrid = new DataGridView();
        ((System.ComponentModel.ISupportInitialize)studentsGrid).BeginInit();
        SuspendLayout();
        layout.Name = "layout";
        layout.TabIndex = 0;
        searchPanel.Name = "searchPanel";
        searchPanel.TabIndex = 1;
        searchPanel.Dock = DockStyle.Fill;
        searchPanel.AutoSize = true;
        searchPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        searchPanel.Padding = new Padding(8);
        fieldsPanel.Name = "fieldsPanel";
        fieldsPanel.TabIndex = 2;
        fieldsPanel.Dock = DockStyle.Fill;
        fieldsPanel.AutoSize = true;
        fieldsPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        fieldsPanel.Padding = new Padding(8);
        actionsPanel.Name = "actionsPanel";
        actionsPanel.TabIndex = 3;
        actionsPanel.Dock = DockStyle.Fill;
        actionsPanel.AutoSize = true;
        actionsPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        actionsPanel.Padding = new Padding(8);
        bulkPanel.Name = "bulkPanel";
        bulkPanel.TabIndex = 4;
        bulkPanel.Dock = DockStyle.Fill;
        bulkPanel.AutoSize = true;
        bulkPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        bulkPanel.Padding = new Padding(8);
        lblSearch.Name = "lblSearch";
        lblSearch.TabIndex = 5;
        lblSearch.AutoSize = true;
        lblSearch.Margin = new Padding(3, 7, 6, 3);
        txtSearch.Name = "txtSearch";
        txtSearch.TabIndex = 6;
        txtSearch.Width = 130;
        btnFind.Name = "btnFind";
        btnFind.TabIndex = 7;
        btnFind.AutoSize = true;
        btnFind.MinimumSize = new Size(100, 32);
        lblRollNo.Name = "lblRollNo";
        lblRollNo.TabIndex = 8;
        lblRollNo.AutoSize = true;
        lblRollNo.Margin = new Padding(3, 7, 6, 3);
        txtRollNo.Name = "txtRollNo";
        txtRollNo.TabIndex = 9;
        txtRollNo.Width = 130;
        lblName.Name = "lblName";
        lblName.TabIndex = 10;
        lblName.AutoSize = true;
        lblName.Margin = new Padding(3, 7, 6, 3);
        txtName.Name = "txtName";
        txtName.TabIndex = 11;
        txtName.Width = 130;
        lblAssignment.Name = "lblAssignment";
        lblAssignment.TabIndex = 12;
        lblAssignment.AutoSize = true;
        lblAssignment.Margin = new Padding(3, 7, 6, 3);
        txtAssignment.Name = "txtAssignment";
        txtAssignment.TabIndex = 13;
        txtAssignment.Width = 130;
        lblExam.Name = "lblExam";
        lblExam.TabIndex = 14;
        lblExam.AutoSize = true;
        lblExam.Margin = new Padding(3, 7, 6, 3);
        txtExam.Name = "txtExam";
        txtExam.TabIndex = 15;
        txtExam.Width = 130;
        btnAdd.Name = "btnAdd";
        btnAdd.TabIndex = 16;
        btnAdd.AutoSize = true;
        btnAdd.MinimumSize = new Size(100, 32);
        btnUpdate.Name = "btnUpdate";
        btnUpdate.TabIndex = 17;
        btnUpdate.AutoSize = true;
        btnUpdate.MinimumSize = new Size(100, 32);
        btnDelete.Name = "btnDelete";
        btnDelete.TabIndex = 18;
        btnDelete.AutoSize = true;
        btnDelete.MinimumSize = new Size(100, 32);
        btnClear.Name = "btnClear";
        btnClear.TabIndex = 19;
        btnClear.AutoSize = true;
        btnClear.MinimumSize = new Size(100, 32);
        lblBulk.Name = "lblBulk";
        lblBulk.TabIndex = 20;
        lblBulk.AutoSize = true;
        lblBulk.Margin = new Padding(3, 7, 6, 3);
        chkName.Name = "chkName";
        chkName.TabIndex = 21;
        chkName.AutoSize = true;
        chkAssignment.Name = "chkAssignment";
        chkAssignment.TabIndex = 22;
        chkAssignment.AutoSize = true;
        chkExam.Name = "chkExam";
        chkExam.TabIndex = 23;
        chkExam.AutoSize = true;
        btnBulkUpdate.Name = "btnBulkUpdate";
        btnBulkUpdate.TabIndex = 24;
        btnBulkUpdate.AutoSize = true;
        btnBulkUpdate.MinimumSize = new Size(100, 32);
        lblStatus.Name = "lblStatus";
        lblStatus.TabIndex = 25;
        lblStatus.AutoSize = true;
        lblStatus.Margin = new Padding(3, 7, 6, 3);
        studentsGrid.Name = "studentsGrid";
        studentsGrid.TabIndex = 26;
        lblSearch.Text = "Roll No";
        btnFind.Text = "Find";
        lblRollNo.Text = "Roll No (auto)";
        lblName.Text = "Name";
        lblAssignment.Text = "Assignment Score";
        lblExam.Text = "Exam Score";
        btnAdd.Text = "Add";
        btnUpdate.Text = "Update";
        btnDelete.Text = "Delete selected";
        btnClear.Text = "Clear";
        lblBulk.Text = "Update these fields:";
        chkName.Text = "Name";
        chkAssignment.Text = "Assignment Score";
        chkExam.Text = "Exam Score";
        btnBulkUpdate.Text = "Update selected";
        lblStatus.Text = "Double-click a grid cell to edit. Enter saves; Esc cancels. Ctrl or Shift selects multiple rows.";
        txtRollNo.ReadOnly = true;
        txtRollNo.TabStop = false;
        txtRollNo.Width = 75;
        txtName.Width = 170;
        txtAssignment.Text = "0";
        txtExam.Text = "0";
        bulkPanel.Visible = false;
        searchPanel.Controls.Add(lblSearch);
        searchPanel.Controls.Add(txtSearch);
        searchPanel.Controls.Add(btnFind);
        fieldsPanel.Controls.Add(lblRollNo);
        fieldsPanel.Controls.Add(txtRollNo);
        fieldsPanel.Controls.Add(lblName);
        fieldsPanel.Controls.Add(txtName);
        fieldsPanel.Controls.Add(lblAssignment);
        fieldsPanel.Controls.Add(txtAssignment);
        fieldsPanel.Controls.Add(lblExam);
        fieldsPanel.Controls.Add(txtExam);
        actionsPanel.Controls.Add(btnAdd);
        actionsPanel.Controls.Add(btnUpdate);
        actionsPanel.Controls.Add(btnDelete);
        actionsPanel.Controls.Add(btnClear);
        bulkPanel.Controls.Add(lblBulk);
        bulkPanel.Controls.Add(chkName);
        bulkPanel.Controls.Add(chkAssignment);
        bulkPanel.Controls.Add(chkExam);
        bulkPanel.Controls.Add(btnBulkUpdate);
        layout.Dock = DockStyle.Fill;
        layout.ColumnCount = 1;
        layout.RowCount = 6;
        layout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.Controls.Add(searchPanel, 0, 0);
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.Controls.Add(fieldsPanel, 0, 1);
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.Controls.Add(actionsPanel, 0, 2);
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.Controls.Add(bulkPanel, 0, 3);
        layout.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        layout.Controls.Add(lblStatus, 0, 4);
        layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        layout.Controls.Add(studentsGrid, 0, 5);
        studentsGrid.Dock = DockStyle.Fill;
        studentsGrid.ReadOnly = false;
        studentsGrid.AllowUserToAddRows = false;
        studentsGrid.AllowUserToDeleteRows = false;
        studentsGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        studentsGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        studentsGrid.MultiSelect = true;
        studentsGrid.EditMode = DataGridViewEditMode.EditOnKeystrokeOrF2;
        studentsGrid.BackgroundColor = SystemColors.Window;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1100, 600);
        MinimumSize = new Size(1000, 500);
        Controls.Add(layout);
        Name = "StudentView";
        Text = "Student Manager";
        ((System.ComponentModel.ISupportInitialize)studentsGrid).EndInit();
        ResumeLayout(false);
        PerformLayout();
    }
}
